import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "../app/styles.css";
import Navbar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <Navbar />
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
